Drop `parsed_call_number` from the xslt
We're not using it and we suspect the empty child nodes (with self
closing tags) may be behind the following exception [1]:

```
SpineOMatic cannot process the XML due to invalid characters in the data.
The error returned is:
System.Xml.XmlException: '_1' is an unexpected token. The expected token is '>'...
    ...
    at SpineLabeler.Form1.getBarcodeFile()
```

[1]: https://github.com/ExLibrisGroup/SpineOMatic/blob/5aafb40bd4268259242d7eb279496f95eee4ece3/Form1.vb#L1458-L1490